{
 "title": "Environment Analysis",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Temp (F)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "SELECT mean(\"temperature_f\") FROM \"environment\" WHERE $timeFilter GROUP BY time($__interval), \"location\"::tag"
    }
   ]
  },
  {
   "title": "Pressure (PA)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "SELECT mean(\"pressure_pa\") FROM \"environment\" WHERE $timeFilter GROUP BY time($__interval), \"location\"::tag"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "SELECT mean(\"humidity\") FROM \"environment\" WHERE $timeFilter GROUP BY time($__interval), \"location\"::tag"
    }
   ]
  },
  {
   "title": "Highs /Lows",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_location $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device_id::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "environment",
     "query": "SELECT min(\"temperature_f\"), max(\"temperature_f\") FROM \"environment\" WHERE $timeFilter and (\"location\" = 'Back Patio' or \"location\" = 'Chris Office') GROUP BY \"location\"::tag fill(null)",
     "select": [
      [
       { "params": [ "temperature_f" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  }
 ]
}